### ISSUE TITLE
Issue using non built-in schema

### ISSUE THREAD

**Issue by bschmoker** [STIXProject/stix-validator#51] opened 2014-12-22 21:02 UTC
@bworrell validator emits errors when given a non-builtin schema to validate against.

Running:
```
pip install stix-validator
git clone https://github.com/STIXProject/schemas.git 
stix_validator --schema-dir schemas examples/all_valid.xml
```

results in:
```
[!] Fatal Error: element decl. '{http://stix.mitre.org/common-1}Time', attribute 'type': The QName value '{http://cybox.mitre.org/common-2}TimeType' does not resolve to a(n) type definition., line 42
```
Same error (and line #) occur on differing input files

Am I using `--schema-dir ` correctly?
(Note: I discovered this bug while writing unit tests for the schema)

**Comment by gtback** [comment] 2015-02-25 14:13
I ran into this same error yesterday, and it was caused by not having the `cybox` submodule cloned (see my instructions above). I added a note to the README to clarify (20a8dc5795694c9edb2f662efaae2d9716967590), as @bworrell suggested.

I'm going to close this, but if you continue to have this problem, @bschmoker, please reopen.

**Closed by gtback** 2015-02-25 14:13 UTC
Labels: bug
